# Supabase PostgreSQL
spring.datasource.url=jdbc:postgresql://db.zuvlthklfwquowtsqxdd.supabase.co:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Root2026.tpo

# Hibernate crea/actualiza tablas automaticamente, sin borrar datos
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 console ya no aplica
spring.h2.console.enabled=false
