spring.application.name=backend
spring.profiles.active=dev
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

app.jwt.secret=SubastaProSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm
app.jwt.access-token-expiration=900000
app.jwt.refresh-token-expiration=604800000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
