spring.application.name=backend
spring.profiles.active=dev
server.port=${PORT:8080}
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource.url=jdbc:postgresql://db.zuvlthklfwquowtsqxdd.supabase.co:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Root2026.tpo

app.jwt.secret=${APP_JWT_SECRET:SubastaProSecretKeyMustBeAtLeast256BitsLongForHS256Algorithm}
app.jwt.access-token-expiration=28800000
app.jwt.refresh-token-expiration=604800000

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
